In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
### Dimensioni
# N -> numero di campioni
# T -> numero di timesteps
# D -> numero di features
# M -> numero di hidden units
# K -> numero di output

In [3]:
# Creiamo dei dati
N = 1
T = 10
D = 3
K = 2
x = np.random.randn(N, T, D)

In [4]:
# RNN didattica
M = 5
i = Input(shape=(T, D))
out = SimpleRNN(M, activation="tanh")(i)
out = Dense(K)(out)
model = Model(i, out)
model.compile(loss="mse", optimizer=Adam(learning_rate=0.1))
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 10, 3)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ (None, 5)                   │              45 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 2)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 57 (228.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
# Predizioni poco utili, giusto per la shape
model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step


array([[-0.75020003,  0.6472115 ]], dtype=float32)

In [6]:
# Vediamo 3 array:
# Il primo array è sicuramente la matrice di pesi input - hidden
# Secondo array è hidden - hidden weights
# Terzo array è il bias
model.layers[1].get_weights()

[array([[ 0.10157305,  0.16050869,  0.26464325,  0.5594422 , -0.5945752 ],
        [-0.728014  , -0.66226774, -0.41900924, -0.8197389 ,  0.6351823 ],
        [-0.01140183,  0.3979755 ,  0.07653278,  0.13516861,  0.29170412]],
       dtype=float32),
 array([[-0.75609493, -0.35442725,  0.06176499,  0.41873094, -0.35149843],
        [ 0.32582623,  0.18588556, -0.3941093 ,  0.8380332 ,  0.0407679 ],
        [ 0.4338794 , -0.54839945,  0.66313744,  0.26243398,  0.04882418],
        [-0.07909212,  0.72839284,  0.60697275,  0.16720591, -0.25848514],
        [ 0.3572825 , -0.09235749, -0.1808193 , -0.15979749, -0.89754575]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [7]:
a, b, c = model.layers[1].get_weights()
a.shape, b.shape, c.shape

((3, 5), (5, 5), (5,))

In [8]:
# Facciamo i calcoli RNN manualmente
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [9]:
h_last = np.zeros(M)
x = x[0]
y_hats = []

In [11]:
for t in range(T):
    h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
    y = h.dot(Wo) + bo
    y_hats.append(y)

    h_last = h

print(y_hats[-1])

[-0.75020001  0.64721152]
